### ISSUE TITLE
Chyba při spouštění aplikace

### ISSUE THREAD

**Issue by suchoss** [HlidacStatu/HlidacStatu#34]
Ahoj, teď po pullnutí jsem zkusil spustit a hned ještě před načtením homepage mi to vrátilo chybu:

**Lib.Search řádek 121**
queryString: `"NOT(id:datasourcesdb) AND (*)"`

**error message:**
```
Dataset:datasourcesdb
ApiResponse:INVALID response
Value: 
ErrorNumber: -10
ErrorDescription: Invalid search query .
ErrorDetail: NOT(id:datasourcesdb) AND (*)

Value does not fall within the expected range.

```
**stack trace:**
```
   at HlidacStatu.Lib.Data.External.DataSets.Search.SearchDataRaw(DataSet ds, String queryString, Int32 page, Int32 pageSize, String sort, Boolean excludeBigProperties, Boolean withHighlighting) in D:\repos\HlidacStatu\HlidacStatu\Lib\Data\External\DataSets\Search.cs:line 128
   at HlidacStatu.Lib.Data.External.DataSets.DataSet.SearchDataRaw(String queryString, Int32 page, Int32 pageSize, String sort, Boolean excludeBigProperties, Boolean withHighlighting) in D:\repos\HlidacStatu\HlidacStatu\Lib\Data\External\DataSets\DataSet.cs:line 150
   at HlidacStatu.Lib.Data.External.DataSets.DataSetDB.SearchDataRaw(String queryString, Int32 page, Int32 pageSize, String sort, Boolean excludeBigProperties, Boolean withHighlighting) in D:\repos\HlidacStatu\HlidacStatu\Lib\Data\External\DataSets\DataSetDb.cs:line 200
   at HlidacStatu.Lib.Data.External.DataSets.DataSetDB.<>c.<.cctor>b__10_0(Object obj) in D:\repos\HlidacStatu\HlidacStatu\Lib\Data\External\DataSets\DataSetDb.cs:line 19
   at Devmasters.Cache.V20.BaseCache`1.GetDataFromContentFunction()
```

**Comment by suchoss** [comment]
Chybu mi to hází na každé stránce. Nejen při spouštění aplikace.

**Comment by michalblaha** [comment]
fixed
